feed/urls.py
from django.urls import path
from .views import HomePageView, PostDetailView, AddPostImageView
app_name = 'feed'


urlpatterns = [
    path("", HomePageView.as_view() , name='index'),
    path("detail/<int:pk>/", PostDetailView.as_view(), name = 'detail'),
    path("post/", AddPostImageView.as_view(), name = 'post'),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf.urls.static import static
from feed import urls as feeds_url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/',include(feeds_url, namespace = 'feed')),
]

if settings.DEBUG:
    urlpatterns +=  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

feed/models.py
from django.db import models
from sorl.thumbnail import ImageField


class Posts(models.Model):
    text = models.CharField(max_length=170, blank=False, null=False)
    image = ImageField()
    created_at = models.DateTimeField(auto_now_add=True, blank=True, null=True)

    def __str__(self) -> str:
        return self.text

likes/models.py
from django.db import models

# Create your models here.
class Likes(models.Model):
    likeCount= models.IntegerField()

    # def __str__(self) -> int:
    #     return self.likeCount

feed/forms.py
from django import forms

class PostForm(forms.Form):
    text = forms.CharField()
    image = forms.FileField()

feed/views.py
from django.shortcuts import render
from django.contrib import messages
from django.views.generic import TemplateView, DetailView, FormView
from .models import Posts
from .forms import PostForm

# Create your views here.
class HomePageView(TemplateView):
    template_name: str = "home.html"

    # This will be used to send data to html
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["my_thing"] = "Hello world coming from dynamic something"
        context["posts"] = Posts.objects.all().order_by("-id")

        return context


class PostDetailView(DetailView):
    template_name: str = "detail.html"
    model = Posts


class AddPostImageView(FormView):
    template_name: str = "form.html"
    success_url = "/home"
    form_class = PostForm

    def dispatch(self, request, *args, **kwargs):
        self.request = request
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        print("This was valid")
        print(form.cleaned_data["text"])
        print(form.cleaned_data["text"])
        print(form.cleaned_data["text"])
        print(form.cleaned_data["text"])
        print(form.cleaned_data["text"])
        new_object = Posts.objects.create(
            text=form.cleaned_data["text"], image=form.cleaned_data["image"]
        )
        messages.add_message(self.request, messages.SUCCESS, "Post has been succesfully created")
        return super().form_valid(form)


# https://ccbv.co.uk/projects/Django/4.1/django.views.generic.base/TemplateView/ for refrence

likes/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Default title{% endblock %}</title>
</head>
<body>
   <h1> {% block body  %}{% endblock%}</h1>
   {% if messages %}
   <ul class="messages">
       {% for message in messages %}
       <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
       {% endfor %}
   </ul>
   {% endif %}
</body>
</html>

templates/detail.html
{% extends "base.html" %}

{% block title %}Detail view{% endblock %}

{% block body %}
    {{object.text}} <br>
    <img src="{{object.image.url}}" alt="">
    
{% endblock %}

templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        <h1>{{form.as_ul}}</h1>
        <div>
            <button type="submit">Click me</button>
        </div>
    </form>
</body>
</html>

templates/home.html
{% extends "base.html" %}


{%block title%}
    some awsome title
{% endblock %}


 
{% block body %}
    {% for post in posts %}
    <a href="{% url 'feed:detail' post.id %}">View details</a>
    {{    post.text}} <br>
    <h1>create at {{post.created_at}}</h1>
   <img src="{{post.image.url}}" alt=""> 
    <hr>
    {% endfor %}
{% endblock%}